FROM ruby:3.2.2

ENV PORT=5173

# Install Node.js, npm, yarn
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get update -qq && apt-get install -y nodejs npm
RUN gem install bundler && gem install rails && npm install -g yarn
RUN npm install -g @vue/cli

RUN mkdir /app
WORKDIR /app
COPY . .
RUN cd /app && bundle install
RUN cd /app && npm install
# Create a directory for the Vue.js build
RUN mkdir -p /app/client/dist

EXPOSE 3000

COPY docker/start-app-prod /usr/local/bin/start-app-prod
RUN chmod +x /usr/local/bin/start-app-prod

ENTRYPOINT [ "start-app-prod" ]