version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
      - '3000:3000'
      - '5173:5173'
    env_file:
      - .env
    networks:
      - namefeeder-net
    volumes:
            - '.:/app'
    depends_on:
        - pgsql
  pgsql:
    container_name: pgsql
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: whatever
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    networks:
      - namefeeder-net
networks:
    namefeeder-net:
        driver: bridge
