#!/usr/bin/env bash
cd /app/client && npm install && npm run build
ln -s /app/client/dist /var/www/namefeeder.com/html
chown -R www-data:www-data /var/www/namefeeder.com/html
chmod -R 755 /var/www/namefeeder.com/html
nginx
nginx -s reload

cd /app && RAILS_ENV=$RAILS_ENV bundle exec rails db:migrate
# cd /app && bundle exec rails s -b '0.0.0.0'
tail -f /dev/null