#!/usr/bin/env bash
cd /app/client && npm install && npm run build
ln -s /app/client/dist /var/www/namefeeder.com/html
chown -R www-data:www-data /var/www
chmod -R 755 /var/www
nginx
nginx -s reload

cd /app && RAILS_ENV=$RAILS_ENV bundle exec rails db:migrate
# cd /app && nohup bundle exec rails s -b '0.0.0.0' > log/development.log 2>&1 &
tail -f /app/log/development.log