#!/usr/bin/env bash
cd /app/client && npm install && npm run build
# Check if the server is already running
if [ -f /app/tmp/pids/server.pid ]; then
  echo "Server is already running. Removing PID file and restarting..."
  rm /app/tmp/pids/server.pid
fi

cd /app && RAILS_ENV=$RAILS_ENV bundle exec rails db:migrate
cd /app && RAILS_ENV=$RAILS_ENV bundle exec puma -p 3000